### ISSUE TITLE
Seed API files from 

### ISSUE THREAD

**Issue by wtrocki** [andreaTP/app-services-backstage#2]
SDK-Core contains all actual versions of the API files. 
We need to add backstage components to the core repository for backstage to automatically pick components from github. 

Previous configuration were seeded manually and have been lost: 
https://github.com/redhat-developer/app-services-sdk-core/tree/doc-portal

**Comment by wtrocki** [comment]
See required config: https://backstage.io/docs/integrations/github/locations
This have been working so far with catalog configuration:

https://backstage.io/docs/features/software-catalog/configuration

@andreaTP I think we need to make decision:

1) Are we seeding components from various github repos and commiting there yaml files.
2) Are we seeding components from backstage github (this repo)
3) Are we including components with the docker image (hardcoded)
4) Are we adding components manually (that was temporary IMHO for demos)

**Comment by wtrocki** [comment]
I think my biased approach would be to change yaml file in the repo (git ops approach) (option 2).
The only thing is that we would need to have multiple folder structures with individual components that we can reference and link.

**Comment by andreaTP** [comment]
Thanks for opening this issue @wtrocki !
A couple of questions:
- What do you think about a provisioning script (e.g. implemented with an init container) to dynamically update the default entries on restarts?
- Do you already have a pre-configured `catalog-info.yaml` I can start with?

**Comment by wtrocki** [comment]
> What do you think about a provisioning script (e.g. implemented with an init container) to dynamically update the default entries on restarts

That can work but it would not be backstage native option. Backstage typically source stuff from github and stores it in db. Database is more or less cache/state representation. That is why I went with SqlLite as my approach was to keep all state on github and only seed config that knows how to pull component info.

> Preconfigured
That is what we have (although it is not loaded in config)

https://github.com/andreaTP/app-services-backstage/blob/main/catalog-info.yaml

**Comment by wtrocki** [comment]
Good part of the postgress db is that we can threat data there as fully persistent and since config for github sources will be trivial we can just do it once manually and keep catalog for local dev.

**Comment by andreaTP** [comment]
Found this as a "backstage native" option:
https://github.com/andreaTP/app-services-backstage/pull/5/files#diff-5cfc849895ab6f4a2eaf9745eec519d828587f17f6575371fe69476d328e2764R11

already integrated to check that everything works as expected in the cluster (had a few issues locally to get it to work)

**Comment by wtrocki** [comment]
Yes. That would be option nr2. Although it would be good to add app-services apis rather than upstream apicurio ones

**Comment by andreaTP** [comment]
> it would be good to add app-services apis rather than upstream apicurio ones

If and when we deploy Backstage along with other app-services I agree 🙂

**Comment by wtrocki** [comment]
Apologies. That was the initial task I got. I have added those APIS manually and that is why I have named  repo app-services-backstage etc. Not sure what is the current target etc .

**Comment by andreaTP** [comment]
Thanks for the input @wtrocki !

Anyhow, this looks to be kind of working as expected (there is a parsing issue I haven't got locally):
https://backstage-apicurio-apicurio-registry.apps.smaug.na.operate-first.cloud/catalog/default/api/apicurio-registry/definition

cc. @paoloantinori 
Here we are exploring/testing adding APIs using this mechanism:
https://github.com/andreaTP/app-services-backstage/blob/d01fea6b864e55df1517d8a7dcabc4b32c08669e/apicurio/registry.yaml#L14

**Comment by paoloantinori** [comment]
that looks nice!
